import struct
import os
import glob

SFX_DIR = os.path.join(os.path.dirname(__file__), '..', 'sfx')
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), '..', 'Core', 'Inc', 'sfx_data.h')

WAV_FILES = [
    ('bgm', 'bgm.wav'),
    ('move', 'move.wav'),
    ('rotate', 'rotate.wav'),
    ('row_clear', 'row_clear.wav'),
    ('row_clear_4', '4_row_clear.wav'),
    ('game_over', 'game_over.wav'),
]

def parse_wav(filepath):
    with open(filepath, 'rb') as f:
        data = f.read()

    riff, file_size, wave = struct.unpack('<4sI4s', data[:12])
    assert riff == b'RIFF' and wave == b'WAVE', f'{filepath}: not a WAV'

    sample_rate = 0
    bits_per_sample = 0
    num_channels = 0
    pcm_data = None

    pos = 12
    while pos < len(data):
        chunk_id, chunk_size = struct.unpack('<4sI', data[pos:pos+8])
        if chunk_id == b'fmt ':
            fmt = data[pos+8:pos+8+min(chunk_size, 16)]
            audio_format, num_channels, sample_rate, byte_rate, block_align, bits_per_sample = \
                struct.unpack('<HHIIHH', fmt[:16])
        elif chunk_id == b'data':
            pcm_data = data[pos+8:pos+8+chunk_size]
        pos += 8 + chunk_size
        if chunk_size % 2:
            pos += 1

    assert pcm_data is not None, f'{filepath}: no data chunk'
    assert bits_per_sample == 8, f'{filepath}: only 8-bit supported, got {bits_per_sample}'
    assert sample_rate == 16000, f'{filepath}: only 16kHz supported, got {sample_rate}Hz'

    samples_16bit = []
    for byte in pcm_data:
        s = (byte - 128) << 8
        samples_16bit.append(s & 0xFFFF)

    return samples_16bit, sample_rate

def generate_c_array(var_name, data, values_per_line=16):
    lines = []
    lines.append(f'static const uint16_t {var_name}[] = {{')
    for i in range(0, len(data), values_per_line):
        chunk = data[i:i+values_per_line]
        lines.append('  ' + ', '.join(f'0x{v:04X}' for v in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    lines = []
    lines.append('// Auto-generated by tools/convert_sfx.py')
    lines.append('#ifndef SFX_DATA_H')
    lines.append('#define SFX_DATA_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')

    info_entries = []
    lengths = {}
    sample_rates = {}

    for enum_name, filename in WAV_FILES:
        filepath = os.path.join(SFX_DIR, filename)
        if not os.path.exists(filepath):
            print(f'WARNING: {filepath} not found, skipping')
            continue

        samples, sr = parse_wav(filepath)
        arr_name = f'sfx_{enum_name}'
        lines.append(generate_c_array(arr_name, samples))
        lines.append('')

        info_entries.append(f'  {{ {arr_name}, {len(samples)}, {sr} }}')
        lengths[enum_name] = len(samples)
        sample_rates[enum_name] = sr

    /* SFX_COUNT is defined in audio.h */

    lines.append('typedef struct {')
    lines.append('  const uint16_t *data;')
    lines.append('  uint32_t length;')
    lines.append('  uint32_t sample_rate;')
    lines.append('} SFX_Info;')
    lines.append('')

    lines.append('static const SFX_Info sfx_info[SFX_COUNT] = {')
    for entry in info_entries:
        lines.append(f'  {entry},')
    lines.append('};')
    lines.append('')

    lines.append('#endif // SFX_DATA_H')
    lines.append('')

    output = '\n'.join(lines)
    with open(OUTPUT_FILE, 'w') as f:
        f.write(output)

    total_samples = sum(lengths.values())
    total_bytes = total_samples * 2
    print(f'Generated {OUTPUT_FILE}')
    print(f'  Files: {len(lengths)}')
    print(f'  Total samples: {total_samples}')
    print(f'  Total size: {total_bytes} bytes ({total_bytes/1024:.1f} KB)')

if __name__ == '__main__':
    main()
